apiVersion: v1
kind: Service
metadata:
  name: simple-lb
spec:
  selector:
    app: simple
  ports:
    - protocol: TCP
      port: 80 # Load Balancer Port
      targetPort: 80 # Container Port
  type: LoadBalancer