apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-pod
spec:
  containers:
  - image: luksa/fortune
    name: html-generator
    volumeMounts:
    - name: html # Volume Name
      mountPath: /var/htdocs # Directory in the container's filesystem
  - image: nginx
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes: 
  - name: html
    emptyDir: {}